--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/28/2023 5:29:26 PM
-- Server version: 10.4.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE nvduong;

--
-- Drop procedure `proc_login`
--
DROP PROCEDURE IF EXISTS proc_login;

--
-- Drop view `view_users`
--
DROP VIEW IF EXISTS view_users CASCADE;

--
-- Drop procedure `proc_user_add`
--
DROP PROCEDURE IF EXISTS proc_user_add;

--
-- Drop procedure `proc_user_del`
--
DROP PROCEDURE IF EXISTS proc_user_del;

--
-- Drop procedure `proc_user_getAll`
--
DROP PROCEDURE IF EXISTS proc_user_getAll;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop procedure `proc_score_getByClass`
--
DROP PROCEDURE IF EXISTS proc_score_getByClass;

--
-- Drop procedure `proc_score_getByStudent`
--
DROP PROCEDURE IF EXISTS proc_score_getByStudent;

--
-- Drop view `view_score`
--
DROP VIEW IF EXISTS view_score CASCADE;

--
-- Drop view `view_score_average`
--
DROP VIEW IF EXISTS view_score_average CASCADE;

--
-- Drop procedure `proc_student_add`
--
DROP PROCEDURE IF EXISTS proc_student_add;

--
-- Drop procedure `proc_score_add`
--
DROP PROCEDURE IF EXISTS proc_score_add;

--
-- Drop procedure `proc_student_add_fakeScore`
--
DROP PROCEDURE IF EXISTS proc_student_add_fakeScore;

--
-- Drop procedure `proc_score_addFake`
--
DROP PROCEDURE IF EXISTS proc_score_addFake;

--
-- Drop procedure `proc_score_update`
--
DROP PROCEDURE IF EXISTS proc_score_update;

--
-- Drop table `scores`
--
DROP TABLE IF EXISTS scores;

--
-- Drop procedure `proc_teacher_getAll`
--
DROP PROCEDURE IF EXISTS proc_teacher_getAll;

--
-- Drop view `view_teachers`
--
DROP VIEW IF EXISTS view_teachers CASCADE;

--
-- Drop procedure `proc_teacher_add`
--
DROP PROCEDURE IF EXISTS proc_teacher_add;

--
-- Drop procedure `proc_teacher_del`
--
DROP PROCEDURE IF EXISTS proc_teacher_del;

--
-- Drop table `teachers`
--
DROP TABLE IF EXISTS teachers;

--
-- Drop view `view_subjects`
--
DROP VIEW IF EXISTS view_subjects CASCADE;

--
-- Drop procedure `proc_subject_add`
--
DROP PROCEDURE IF EXISTS proc_subject_add;

--
-- Drop procedure `proc_subject_del`
--
DROP PROCEDURE IF EXISTS proc_subject_del;

--
-- Drop procedure `proc_subject_getAll`
--
DROP PROCEDURE IF EXISTS proc_subject_getAll;

--
-- Drop table `subjects`
--
DROP TABLE IF EXISTS subjects;

--
-- Drop procedure `proc_class_getAll`
--
DROP PROCEDURE IF EXISTS proc_class_getAll;

--
-- Drop view `view_classes`
--
DROP VIEW IF EXISTS view_classes CASCADE;

--
-- Drop procedure `proc_student_class`
--
DROP PROCEDURE IF EXISTS proc_student_class;

--
-- Drop view `view_student`
--
DROP VIEW IF EXISTS view_student CASCADE;

--
-- Drop procedure `proc_student_del`
--
DROP PROCEDURE IF EXISTS proc_student_del;

--
-- Drop procedure `proc_student_getById`
--
DROP PROCEDURE IF EXISTS proc_student_getById;

--
-- Drop procedure `proc_student_update`
--
DROP PROCEDURE IF EXISTS proc_student_update;

--
-- Drop table `students`
--
DROP TABLE IF EXISTS students;

--
-- Drop view `view_teaching`
--
DROP VIEW IF EXISTS view_teaching CASCADE;

--
-- Drop procedure `proc_teacherClass_add`
--
DROP PROCEDURE IF EXISTS proc_teacherClass_add;

--
-- Drop procedure `proc_teacherClass_del`
--
DROP PROCEDURE IF EXISTS proc_teacherClass_del;

--
-- Drop table `teacherclasses`
--
DROP TABLE IF EXISTS teacherclasses;

--
-- Drop procedure `proc_class_add`
--
DROP PROCEDURE IF EXISTS proc_class_add;

--
-- Drop procedure `proc_class_del`
--
DROP PROCEDURE IF EXISTS proc_class_del;

--
-- Drop procedure `proc_class_getById`
--
DROP PROCEDURE IF EXISTS proc_class_getById;

--
-- Drop table `classes`
--
DROP TABLE IF EXISTS classes;

--
-- Set default database
--
USE nvduong;

--
-- Create table `classes`
--
CREATE TABLE classes (
  classId varchar(36) NOT NULL DEFAULT '',
  name varchar(10) NOT NULL DEFAULT '',
  schoolYear int(11) NOT NULL,
  PRIMARY KEY (classId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2520,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UNIQUE_name_schoolYear` on table `classes`
--
ALTER TABLE classes
ADD UNIQUE INDEX UNIQUE_name_schoolYear (name, schoolYear);

DELIMITER $$

--
-- Create procedure `proc_class_getById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_class_getById (IN classId char(36))
BEGIN
  SELECT
    c.classId,
    c.name,
    c.schoolYear,
    c.schoolYear + 3 AS 'schoolYearEnd'
  FROM classes c
  WHERE c.classId = classId;
END
$$

--
-- Create procedure `proc_class_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_class_del (IN classId char(36))
BEGIN
  DELETE
    FROM classes
  WHERE classes.classId = classId;
END
$$

--
-- Create procedure `proc_class_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_class_add (IN name varchar(50), IN schoolYear int)
BEGIN
  INSERT INTO classes (classId, name, schoolYear)
    VALUES (UUID(), name, schoolYear);

  SELECT
    *
  FROM classes;

END
$$

DELIMITER ;

--
-- Create table `teacherclasses`
--
CREATE TABLE teacherclasses (
  classId char(36) NOT NULL DEFAULT '',
  teacherId char(36) NOT NULL DEFAULT '',
  semester int(11) NOT NULL,
  year int(11) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_teacherclasses` on table `teacherclasses`
--
ALTER TABLE teacherclasses
ADD UNIQUE INDEX UK_teacherclasses (classId, teacherId, semester, year);

--
-- Create foreign key
--
ALTER TABLE teacherclasses
ADD CONSTRAINT FK_teacherclasses_classId FOREIGN KEY (classId)
REFERENCES classes (classId);

DELIMITER $$

--
-- Create procedure `proc_teacherClass_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_teacherClass_del (IN teacherId char(36), IN classId char(36))
BEGIN
  DELETE
    FROM teacherclasses
  WHERE (teacherclasses.teacherId = teacherId
    && teacherclasses.classId = classId);
END
$$

--
-- Create procedure `proc_teacherClass_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_teacherClass_add (IN teacherId char(36), IN classId char(36), IN semester smallint, IN year int)
BEGIN
  INSERT INTO teacherclasses (classId, teacherId, semester, year)
    VALUES (classId, teacherId, semester, year);
END
$$

DELIMITER ;

--
-- Create view `view_teaching`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_teaching
AS
SELECT
  `teacherclasses`.`teacherId` AS `teacherId`,
  `teacherclasses`.`classId` AS `classId`,
  `teacherclasses`.`semester` AS `semester`,
  `teacherclasses`.`year` AS `year`
FROM `teacherclasses`;

--
-- Create table `students`
--
CREATE TABLE students (
  studentId char(36) NOT NULL DEFAULT '',
  firstName varchar(50) NOT NULL DEFAULT '',
  lastName varchar(50) NOT NULL DEFAULT '',
  classId char(36) NOT NULL DEFAULT '',
  dob date DEFAULT NULL,
  studentCode int(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  admissionYear smallint(6) DEFAULT NULL,
  fatherName varchar(50) DEFAULT NULL,
  fatherPhone varchar(20) DEFAULT NULL,
  motherName varchar(50) DEFAULT NULL,
  motherPhone varchar(20) DEFAULT NULL,
  ethnic varchar(20) DEFAULT NULL,
  fatherJob varchar(50) DEFAULT NULL,
  motherJob varchar(50) DEFAULT NULL,
  PRIMARY KEY (studentCode)
)
ENGINE = INNODB,
AUTO_INCREMENT = 85,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `studentId` on table `students`
--
ALTER TABLE students
ADD UNIQUE INDEX studentId (studentId);

--
-- Create foreign key
--
ALTER TABLE students
ADD CONSTRAINT FK_students_classId FOREIGN KEY (classId)
REFERENCES classes (classId);

DELIMITER $$

--
-- Create procedure `proc_student_update`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_update (IN studentId char(36), IN firstName varchar(50), IN lastName varchar(50), IN dob date, IN ethnic varchar(20), IN fatherName varchar(50), IN fatherPhone varchar(20), IN fatherJob varchar(20), IN motherName varchar(50), IN motherPhone varchar(20), IN motherJob varchar(20), IN classId char(36))
BEGIN
  UPDATE students s
  SET s.firstName = firstName,
      s.lastName = lastName,
      s.classId = classId,
      s.dob = dob,
      s.fatherName = fatherName,
      s.fatherPhone = fatherPhone,
      s.motherName = motherName,
      s.motherPhone = motherPhone,
      s.ethnic = ethnic,
      s.fatherJob = fatherJob,
      s.motherJob = motherJob
  WHERE s.studentId = studentId;
  SELECT
    *
  FROM students s
  WHERE s.studentId = studentId;

END
$$

--
-- Create procedure `proc_student_getById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_getById (IN studentId varchar(255))
BEGIN
  SELECT
    s.studentId,
    s.firstName,
    s.lastName,
    CONCAT(s.lastName, ' ', s.firstName) AS fullName,
    s.classId,
    s.dob,
    s.studentCode,
    s.admissionYear,
    s.fatherName,
    s.fatherPhone,
    s.motherName,
    s.motherPhone,
    s.ethnic,
    s.fatherJob,
    s.motherJob
  FROM students s
  WHERE s.studentId = studentId;
END
$$

--
-- Create procedure `proc_student_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_del (IN studentId char(36))
BEGIN
  DELETE
    FROM students
  WHERE students.studentId = studentId;
END
$$

DELIMITER ;

--
-- Create view `view_student`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_student
AS
SELECT
  `s`.`studentId` AS `studentId`,
  `s`.`firstName` AS `firstName`,
  `s`.`lastName` AS `lastName`,
  `s`.`classId` AS `classId`,
  `s`.`dob` AS `dob`,
  `s`.`studentCode` AS `studentCode`,
  `s`.`admissionYear` AS `admissionYear`,
  `s`.`fatherName` AS `fatherName`,
  `s`.`fatherPhone` AS `fatherPhone`,
  `s`.`motherName` AS `motherName`,
  `s`.`motherPhone` AS `motherPhone`,
  `s`.`ethnic` AS `ethnic`,
  `s`.`fatherJob` AS `fatherJob`,
  `s`.`motherJob` AS `motherJob`,
  CONCAT(`s`.`lastName`, ' ', `s`.`firstName`) AS `fullname`,
  `c`.`name` AS `name`,
  `c`.`schoolYear` AS `schoolYear`
FROM (`students` `s`
  LEFT JOIN `classes` `c`
    ON (`s`.`classId` = `c`.`classId`));

DELIMITER $$

--
-- Create procedure `proc_student_class`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_class (IN classId char(36))
BEGIN
  SELECT
    *
  FROM view_student vs
  WHERE vs.classId = classId;
END
$$

DELIMITER ;

--
-- Create view `view_classes`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_classes
AS
SELECT
  `c`.`classId` AS `classId`,
  `c`.`name` AS `name`,
  `c`.`schoolYear` AS `schoolYear`,
  `c`.`schoolYear` + 3 AS `schoolYearEnd`,
  COUNT(`s`.`studentId`) AS `qlt`
FROM (`classes` `c`
  LEFT JOIN `students` `s`
    ON (`c`.`classId` = `s`.`classId`))
GROUP BY `c`.`classId`
ORDER BY `c`.`schoolYear` DESC;

DELIMITER $$

--
-- Create procedure `proc_class_getAll`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_class_getAll ()
BEGIN
  SELECT
    *
  FROM view_classes vc;
END
$$

DELIMITER ;

--
-- Create table `subjects`
--
CREATE TABLE subjects (
  subjectId char(3) NOT NULL DEFAULT '' COMMENT 'id môn học',
  subjectCode varchar(10) NOT NULL DEFAULT '' COMMENT 'mã môn học',
  name varchar(50) NOT NULL DEFAULT '' COMMENT 'tên môn học',
  type smallint(6) DEFAULT 0 COMMENT 'type = 0 tính diểm; type = 1 điều kiện',
  PRIMARY KEY (subjectId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `subjectCode` on table `subjects`
--
ALTER TABLE subjects
ADD UNIQUE INDEX subjectCode (subjectCode);

DELIMITER $$

--
-- Create procedure `proc_subject_getAll`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_subject_getAll ()
BEGIN
  SELECT
    *
  FROM subjects s;

END
$$

--
-- Create procedure `proc_subject_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_subject_del (IN subjectId char(36))
BEGIN
  DELETE
    FROM subjects
  WHERE subjects.subjectId = subjectId;
END
$$

--
-- Create procedure `proc_subject_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_subject_add (IN subjectCode varchar(10), IN name varchar(50), IN type smallint)
BEGIN

  INSERT INTO subjects (subjectId, subjectCode, name, type, subjectCode)
    VALUES (UUID(), subjectCode, name, type);
END
$$

DELIMITER ;

--
-- Create view `view_subjects`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_subjects
AS
SELECT
  `s`.`subjectId` AS `subjectId`,
  `s`.`subjectCode` AS `subjectCode`,
  `s`.`name` AS `name`,
  `s`.`type` AS `type`
FROM `subjects` `s`;

--
-- Create table `teachers`
--
CREATE TABLE teachers (
  teacherId char(36) NOT NULL DEFAULT '',
  firstName varchar(50) DEFAULT NULL,
  lastName varchar(50) DEFAULT NULL,
  phone varchar(50) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT '',
  subjectId char(3) DEFAULT NULL,
  teacherCode int(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (teacherCode)
)
ENGINE = INNODB,
AUTO_INCREMENT = 34,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `email` on table `teachers`
--
ALTER TABLE teachers
ADD UNIQUE INDEX email (email);

--
-- Create index `phone` on table `teachers`
--
ALTER TABLE teachers
ADD UNIQUE INDEX phone (phone);

--
-- Create index `teacherId` on table `teachers`
--
ALTER TABLE teachers
ADD UNIQUE INDEX teacherId (teacherId);

--
-- Create foreign key
--
ALTER TABLE teachers
ADD CONSTRAINT FK_teachers_subjectId FOREIGN KEY (subjectId)
REFERENCES subjects (subjectId);

DELIMITER $$

--
-- Create procedure `proc_teacher_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_teacher_del (IN teacherId char(36))
BEGIN
  DELETE
    FROM teachers
  WHERE teachers.teacherId = teacherId;
END
$$

--
-- Create procedure `proc_teacher_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_teacher_add (IN firstName varchar(50), IN lastName varchar(50), IN phone varchar(20), IN email varchar(50), IN subjectId char(3))
BEGIN
  INSERT INTO teachers
    VALUES (UUID(), firstName, lastName, phone, email, subjectId, 0);
END
$$

DELIMITER ;

--
-- Create view `view_teachers`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_teachers
AS
SELECT
  `t`.`teacherId` AS `teacherId`,
  `t`.`firstName` AS `firstName`,
  `t`.`lastName` AS `lastName`,
  CONCAT(`t`.`lastName`, ' ', `t`.`firstName`) AS `fullname`,
  `t`.`phone` AS `phone`,
  `t`.`email` AS `email`,
  `t`.`subjectId` AS `subjectId`,
  `t`.`teacherCode` AS `teacherCode`,
  `s`.`name` AS `subjectName`
FROM (`teachers` `t`
  LEFT JOIN `subjects` `s`
    ON (`t`.`subjectId` = `s`.`subjectId`));

DELIMITER $$

--
-- Create procedure `proc_teacher_getAll`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_teacher_getAll ()
BEGIN
  SELECT
    *
  FROM view_teachers vt;
END
$$

DELIMITER ;

--
-- Create table `scores`
--
CREATE TABLE scores (
  studentId char(36) NOT NULL DEFAULT '',
  classId char(36) NOT NULL DEFAULT '',
  subjectId char(3) NOT NULL DEFAULT '',
  semester smallint(6) NOT NULL,
  oralTest float DEFAULT 0,
  fifTest1 float DEFAULT 0,
  fifTest2 float DEFAULT 0,
  periodTest1 float DEFAULT 0,
  periodTest2 float DEFAULT 0,
  finalTest float DEFAULT NULL,
  year int(11) NOT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 210,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create check constraint
--
ALTER TABLE scores
ADD CONSTRAINT CK_scores CHECK (`year` BETWEEN 1 AND 3);

--
-- Create index `UK_scores` on table `scores`
--
ALTER TABLE scores
ADD UNIQUE INDEX UK_scores (studentId, classId, subjectId, semester, year);

--
-- Create foreign key
--
ALTER TABLE scores
ADD CONSTRAINT FK_scores_classId FOREIGN KEY (classId)
REFERENCES classes (classId);

--
-- Create foreign key
--
ALTER TABLE scores
ADD CONSTRAINT FK_scores_studentId FOREIGN KEY (studentId)
REFERENCES students (studentId) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE scores
ADD CONSTRAINT FK_scores_subjectId FOREIGN KEY (subjectId)
REFERENCES subjects (subjectId);

DELIMITER $$

--
-- Create procedure `proc_score_update`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_score_update (IN studentId char(36), IN classId char(36), IN subjectId char(3), IN year smallint, IN semester smallint, IN oralTest float, IN fifTest1 float, IN fifTest2 float, IN periodTest1 float, IN periodTest2 float, IN finalTest float)
BEGIN
  UPDATE scores s
  SET s.oralTest = oralTest,
      s.fifTest1 = fifTest1,
      s.fifTest2 = fifTest2,
      s.periodTest1 = periodTest1,
      s.periodTest2 = periodTest2,
      s.finalTest = finalTest
  WHERE s.studentId = studentId
  AND s.classId = classId
  AND s.subjectId = subjectId
  AND s.year = year
  AND s.semester = semester;
END
$$

--
-- Create procedure `proc_score_addFake`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_score_addFake (IN studentId char(36), IN classId char(36), IN subjectId char(3), IN semester smallint, IN year int)
BEGIN
  INSERT INTO scores (studentId, classId, subjectId, semester, oralTest, fifTest1, fifTest2, periodTest1, periodTest2, finalTest, year)
    VALUES (studentId, classId, subjectId, semester, FLOOR(RAND() * 10 + 1), FLOOR(RAND() * 10 + 1), FLOOR(RAND() * 10 + 1), FLOOR(RAND() * 10 + 1), FLOOR(RAND() * 10 + 1), FLOOR(RAND() * 10 + 1), year);
END
$$

--
-- Create procedure `proc_student_add_fakeScore`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_add_fakeScore (IN firstName varchar(50), IN lastName varchar(50), IN ethnic varchar(20), IN classId char(36), IN dob date, IN fatherName varchar(50), IN fatherPhone varchar(50), IN fatherJob varchar(50), IN motherName varchar(50), IN motherPhone varchar(50), IN motherJob varchar(50))
BEGIN
  SET @ID := UUID();
  INSERT INTO students (studentId, firstName, lastName, classId, dob, studentCode, admissionYear, fatherName, fatherPhone, motherName, motherPhone, ethnic, fatherJob, motherJob)
    VALUES (@ID, firstName, lastName, classId, dob, 0, 0, fatherName, fatherPhone, motherName, motherPhone, ethnic, fatherJob, motherJob);
  CALL proc_score_addFake(@ID, classId, 's01', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's02', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's03', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's04', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's05', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's06', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's07', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's08', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's09', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's10', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's11', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's12', 1, 1);
  CALL proc_score_addFake(@ID, classId, 's13', 1, 1);

  CALL proc_score_addFake(@ID, classId, 's01', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's02', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's03', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's04', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's05', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's06', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's07', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's08', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's09', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's10', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's11', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's12', 2, 1);
  CALL proc_score_addFake(@ID, classId, 's13', 2, 1);

  CALL proc_score_addFake(@ID, classId, 's01', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's02', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's03', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's04', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's05', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's06', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's07', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's08', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's09', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's10', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's11', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's12', 1, 2);
  CALL proc_score_addFake(@ID, classId, 's13', 1, 2);

  CALL proc_score_addFake(@ID, classId, 's01', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's02', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's03', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's04', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's05', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's06', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's07', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's08', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's09', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's10', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's11', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's12', 2, 2);
  CALL proc_score_addFake(@ID, classId, 's13', 2, 2);

  CALL proc_score_addFake(@ID, classId, 's01', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's02', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's03', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's04', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's05', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's06', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's07', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's08', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's09', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's10', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's11', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's12', 1, 3);
  CALL proc_score_addFake(@ID, classId, 's13', 1, 3);

  CALL proc_score_addFake(@ID, classId, 's01', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's02', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's03', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's04', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's05', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's06', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's07', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's08', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's09', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's10', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's11', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's12', 2, 3);
  CALL proc_score_addFake(@ID, classId, 's13', 2, 3);

END
$$

--
-- Create procedure `proc_score_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_score_add (IN studentId char(36), IN classId char(36), IN subjectId char(3), IN semester smallint, IN year int)
BEGIN
  INSERT INTO scores (studentId, classId, subjectId, semester, oralTest, fifTest1, fifTest2, periodTest1, periodTest2, finalTest, year)
    VALUES (studentId, classId, subjectId, semester, NULL, NULL, NULL, NULL, NULL, NULL, year);
END
$$

--
-- Create procedure `proc_student_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_student_add (IN firstName varchar(50), IN lastName varchar(50), IN ethnic varchar(20), IN classId char(36), IN dob date, IN fatherName varchar(50), IN fatherPhone varchar(50), IN fatherJob varchar(50), IN motherName varchar(50), IN motherPhone varchar(50), IN motherJob varchar(50))
BEGIN
  SET @ID := UUID();
  INSERT INTO students (studentId, firstName, lastName, classId, dob, studentCode, admissionYear, fatherName, fatherPhone, motherName, motherPhone, ethnic, fatherJob, motherJob)
    VALUES (@ID, firstName, lastName, classId, dob, 0, 0, fatherName, fatherPhone, motherName, motherPhone, ethnic, fatherJob, motherJob);
  CALL proc_score_add(@ID, classId, 's01', 1, 1);
  CALL proc_score_add(@ID, classId, 's02', 1, 1);
  CALL proc_score_add(@ID, classId, 's03', 1, 1);
  CALL proc_score_add(@ID, classId, 's04', 1, 1);
  CALL proc_score_add(@ID, classId, 's05', 1, 1);
  CALL proc_score_add(@ID, classId, 's06', 1, 1);
  CALL proc_score_add(@ID, classId, 's07', 1, 1);
  CALL proc_score_add(@ID, classId, 's08', 1, 1);
  CALL proc_score_add(@ID, classId, 's09', 1, 1);
  CALL proc_score_add(@ID, classId, 's10', 1, 1);
  CALL proc_score_add(@ID, classId, 's11', 1, 1);
  CALL proc_score_add(@ID, classId, 's12', 1, 1);
  CALL proc_score_add(@ID, classId, 's13', 1, 1);

  CALL proc_score_add(@ID, classId, 's01', 2, 1);
  CALL proc_score_add(@ID, classId, 's02', 2, 1);
  CALL proc_score_add(@ID, classId, 's03', 2, 1);
  CALL proc_score_add(@ID, classId, 's04', 2, 1);
  CALL proc_score_add(@ID, classId, 's05', 2, 1);
  CALL proc_score_add(@ID, classId, 's06', 2, 1);
  CALL proc_score_add(@ID, classId, 's07', 2, 1);
  CALL proc_score_add(@ID, classId, 's08', 2, 1);
  CALL proc_score_add(@ID, classId, 's09', 2, 1);
  CALL proc_score_add(@ID, classId, 's10', 2, 1);
  CALL proc_score_add(@ID, classId, 's11', 2, 1);
  CALL proc_score_add(@ID, classId, 's12', 2, 1);
  CALL proc_score_add(@ID, classId, 's13', 2, 1);

  CALL proc_score_add(@ID, classId, 's01', 1, 2);
  CALL proc_score_add(@ID, classId, 's02', 1, 2);
  CALL proc_score_add(@ID, classId, 's03', 1, 2);
  CALL proc_score_add(@ID, classId, 's04', 1, 2);
  CALL proc_score_add(@ID, classId, 's05', 1, 2);
  CALL proc_score_add(@ID, classId, 's06', 1, 2);
  CALL proc_score_add(@ID, classId, 's07', 1, 2);
  CALL proc_score_add(@ID, classId, 's08', 1, 2);
  CALL proc_score_add(@ID, classId, 's09', 1, 2);
  CALL proc_score_add(@ID, classId, 's10', 1, 2);
  CALL proc_score_add(@ID, classId, 's11', 1, 2);
  CALL proc_score_add(@ID, classId, 's12', 1, 2);
  CALL proc_score_add(@ID, classId, 's13', 1, 2);

  CALL proc_score_add(@ID, classId, 's01', 2, 2);
  CALL proc_score_add(@ID, classId, 's02', 2, 2);
  CALL proc_score_add(@ID, classId, 's03', 2, 2);
  CALL proc_score_add(@ID, classId, 's04', 2, 2);
  CALL proc_score_add(@ID, classId, 's05', 2, 2);
  CALL proc_score_add(@ID, classId, 's06', 2, 2);
  CALL proc_score_add(@ID, classId, 's07', 2, 2);
  CALL proc_score_add(@ID, classId, 's08', 2, 2);
  CALL proc_score_add(@ID, classId, 's09', 2, 2);
  CALL proc_score_add(@ID, classId, 's10', 2, 2);
  CALL proc_score_add(@ID, classId, 's11', 2, 2);
  CALL proc_score_add(@ID, classId, 's12', 2, 2);
  CALL proc_score_add(@ID, classId, 's13', 2, 2);

  CALL proc_score_add(@ID, classId, 's01', 1, 3);
  CALL proc_score_add(@ID, classId, 's02', 1, 3);
  CALL proc_score_add(@ID, classId, 's03', 1, 3);
  CALL proc_score_add(@ID, classId, 's04', 1, 3);
  CALL proc_score_add(@ID, classId, 's05', 1, 3);
  CALL proc_score_add(@ID, classId, 's06', 1, 3);
  CALL proc_score_add(@ID, classId, 's07', 1, 3);
  CALL proc_score_add(@ID, classId, 's08', 1, 3);
  CALL proc_score_add(@ID, classId, 's09', 1, 3);
  CALL proc_score_add(@ID, classId, 's10', 1, 3);
  CALL proc_score_add(@ID, classId, 's11', 1, 3);
  CALL proc_score_add(@ID, classId, 's12', 1, 3);
  CALL proc_score_add(@ID, classId, 's13', 1, 3);

  CALL proc_score_add(@ID, classId, 's01', 2, 3);
  CALL proc_score_add(@ID, classId, 's02', 2, 3);
  CALL proc_score_add(@ID, classId, 's03', 2, 3);
  CALL proc_score_add(@ID, classId, 's04', 2, 3);
  CALL proc_score_add(@ID, classId, 's05', 2, 3);
  CALL proc_score_add(@ID, classId, 's06', 2, 3);
  CALL proc_score_add(@ID, classId, 's07', 2, 3);
  CALL proc_score_add(@ID, classId, 's08', 2, 3);
  CALL proc_score_add(@ID, classId, 's09', 2, 3);
  CALL proc_score_add(@ID, classId, 's10', 2, 3);
  CALL proc_score_add(@ID, classId, 's11', 2, 3);
  CALL proc_score_add(@ID, classId, 's12', 2, 3);
  CALL proc_score_add(@ID, classId, 's13', 2, 3);

END
$$

DELIMITER ;

--
-- Create view `view_score_average`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_score_average
AS
SELECT
  `s`.`studentId` AS `studentId`,
  `s`.`classId` AS `classId`,
  `s`.`subjectId` AS `subjectId`,
  `s`.`semester` AS `semester`,
  `s`.`year` AS `year`,
  AVG(`s`.`oralTest` + `s`.`fifTest1` + `s`.`fifTest2` + `s`.`periodTest1` * 2 + `s`.`periodTest2` * 2 + `s`.`finalTest` * 3) / 10 AS `average`
FROM `scores` `s`
GROUP BY `s`.`studentId`,
         `s`.`classId`,
         `s`.`subjectId`,
         `s`.`semester`,
         `s`.`year`;

--
-- Create view `view_score`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_score
AS
SELECT
  `s`.`studentId` AS `studentId`,
  `s1`.`studentCode` AS `studentCode`,
  `s1`.`lastName` AS `lastName`,
  CONCAT(`s1`.`lastName`, ' ', `s1`.`firstName`) AS `fullName`,
  `s1`.`firstName` AS `firstName`,
  `s`.`classId` AS `classId`,
  `s`.`subjectId` AS `subjectId`,
  `s2`.`name` AS `subjectName`,
  `s`.`semester` AS `semester`,
  `s`.`oralTest` AS `oralTest`,
  `s`.`fifTest1` AS `fifTest1`,
  `s`.`fifTest2` AS `fifTest2`,
  `s`.`periodTest1` AS `periodTest1`,
  `s`.`periodTest2` AS `periodTest2`,
  `s`.`finalTest` AS `finalTest`,
  `s`.`year` AS `year`,
  `vsa`.`average` AS `average`
FROM (((`scores` `s`
  LEFT JOIN `view_score_average` `vsa`
    ON (`s`.`studentId` = `vsa`.`studentId`
    AND `s`.`classId` = `vsa`.`classId`
    AND `s`.`semester` = `vsa`.`semester`
    AND `s`.`year` = `vsa`.`year`
    AND `s`.`subjectId` = `vsa`.`subjectId`))
  LEFT JOIN `subjects` `s2`
    ON (`s`.`subjectId` = `s2`.`subjectId`))
  LEFT JOIN `students` `s1`
    ON (`s`.`studentId` = `s1`.`studentId`));

DELIMITER $$

--
-- Create procedure `proc_score_getByStudent`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_score_getByStudent (IN studentId char(36), IN semester smallint, IN year smallint)
BEGIN
  SELECT
    *
  FROM view_score vs
  WHERE vs.studentId = studentId
  AND vs.semester = semester
  AND vs.year = year;

END
$$

--
-- Create procedure `proc_score_getByClass`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_score_getByClass (IN classId char(36), IN year smallint, IN semester smallint)
BEGIN
  SELECT
    *
  FROM view_score vs
  WHERE vs.classId = classId
  AND vs.year = year
  AND vs.semester = semester;
END
$$

DELIMITER ;

--
-- Create table `users`
--
CREATE TABLE users (
  userId char(36) NOT NULL DEFAULT '',
  name varchar(50) NOT NULL DEFAULT '',
  username varchar(50) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT '',
  password varchar(50) NOT NULL DEFAULT '',
  level smallint(6) NOT NULL,
  PRIMARY KEY (userId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `email` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX email (email);

--
-- Create index `username` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX username (username);

DELIMITER $$

--
-- Create procedure `proc_user_getAll`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_user_getAll ()
BEGIN
  SELECT
    *
  FROM users u;
END
$$

--
-- Create procedure `proc_user_del`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_user_del (IN userId char(36))
BEGIN
  DELETE
    FROM users
  WHERE users.userId = userId;
END
$$

--
-- Create procedure `proc_user_add`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_user_add (IN name varchar(50), IN userName varchar(50), IN email varchar(50), IN password varchar(50), IN level smallint)
BEGIN
  INSERT INTO users
    VALUE (UUID(), name, userName, email, password, level);
END
$$

DELIMITER ;

--
-- Create view `view_users`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view_users
AS
SELECT
  `users`.`userId` AS `userId`,
  `users`.`name` AS `name`,
  `users`.`username` AS `username`,
  `users`.`email` AS `email`,
  `users`.`password` AS `password`,
  `users`.`level` AS `level`
FROM `users`;

DELIMITER $$

--
-- Create procedure `proc_login`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE proc_login (IN login varchar(255), IN password varchar(255))
BEGIN
  SELECT
    u.userId,
    u.name,
    u.username,
    u.email,
    u.level
  FROM users u
  WHERE password = u.password
  AND (login = u.email
  OR login = u.username);
END
$$

DELIMITER ;

-- 
-- Dumping data for table classes
--
INSERT INTO classes VALUES
('d3b81196-8d3a-11ee-992a-1063c83412cc', 'A1', 2023),
('c18682fb-8d3d-11ee-992a-1063c83412cc', 'A10', 2023),
('c2f9999b-8d3d-11ee-992a-1063c83412cc', 'A11', 2023),
('c451f850-8d3d-11ee-992a-1063c83412cc', 'A12', 2023),
('bb4e709c-8d35-11ee-992a-1063c83412cc', 'A2', 2023),
('2a93ef15-8d3e-11ee-992a-1063c83412cc', 'A2', 2024),
('b480c298-8d3d-11ee-992a-1063c83412cc', 'A3', 2023),
('b6c4d852-8d3d-11ee-992a-1063c83412cc', 'A4', 2023),
('b8663f89-8d3d-11ee-992a-1063c83412cc', 'A5', 2023),
('ba02cd0d-8d3d-11ee-992a-1063c83412cc', 'A6', 2023),
('bb96c64b-8d3d-11ee-992a-1063c83412cc', 'A7', 2023),
('bd29ad98-8d3d-11ee-992a-1063c83412cc', 'A8', 2023),
('bed9cac7-8d3d-11ee-992a-1063c83412cc', 'A9', 2023);

-- 
-- Dumping data for table subjects
--
INSERT INTO subjects VALUES
('s01', 'T', 'Toán', 0),
('s02', 'VL', 'Vật lý', 0),
('s03', 'HH', 'Hoá học', 0),
('s04', 'SH', 'Sinh học', 0),
('s05', 'TH', 'Tin Học', 0),
('s06', 'NV', 'Ngữ Văn', 0),
('s07', 'LS', 'Lịch sử', 0),
('s08', 'ĐL', 'Địa lý', 0),
('s09', 'TA', 'Tiếng Anh', 0),
('s10', 'GDCD', 'Giáo dục công dân', 0),
('s11', 'CN', 'Công nghệ', 0),
('s12', 'TD', 'Thể dục', 1),
('s13', 'QPAN', 'Quốc phòng an ninh', 0);

-- 
-- Dumping data for table students
--
INSERT INTO students VALUES
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'Nguyễn', 'Dương', 'd3b81196-8d3a-11ee-992a-1063c83412cc', '2023-11-22', 000084, 0, 'Nguyễn Văn A', '0337273658', 'Nguyễn Thị Hoa', '0337273658', 'Kinh', 'Công nhân', 'Công nhân');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('2cebd49a-8d1f-11ee-992a-1063c83412cc', 'Nguyễn Văn Dương', 'nvduong', 'nvduong@gmail.com', '123456', 0),
('75cefe07-8d40-11ee-992a-1063c83412cc', 'Nguyễn Văn Đức', 'nvduc', 'nvduc@gmail.com', '123456', 1);

-- 
-- Dumping data for table teachers
--
INSERT INTO teachers VALUES
('276b4834-8d3a-11ee-992a-1063c83412cc', 'Cường', 'Nguyễn Văn ', '0987654321', 'cuongnv@gmail.com', 's01', 025),
('7110893e-8d3c-11ee-992a-1063c83412cc', 'Nguyễn', 'Dương', '0337273658', 'c3tanlaphanoi@gmail.com', 's02', 026),
('775a95bd-8d3c-11ee-992a-1063c83412cc', 'Nguyễn2', 'Dương2', '03372736582', 'c3tanlaphanoi@gmail.com2', 's04', 027),
('7b077ed7-8d3c-11ee-992a-1063c83412cc', 'Nguyễn23', 'Dương23', '033727365823', 'c3tanlaphanoi@gmail.com23', 's03', 028),
('7fb3350d-8d3c-11ee-992a-1063c83412cc', 'Nguyễn231', 'Dương231', '0337273658231', 'c3tanlaphanoi@gmail.com231', 's05', 029),
('8356c2d3-8d3c-11ee-992a-1063c83412cc', 'Nguyễn2312', 'Dương2312', '03372736582312', 'c3tanlaphanoi@gmail.com2312', 's06', 030),
('8688b57a-8d3c-11ee-992a-1063c83412cc', 'Nguyễn23123', 'Dương23123', '033727365823123', 'c3tanlaphanoi@gmail.com23123', 's07', 031),
('897195e3-8d3c-11ee-992a-1063c83412cc', 'Nguyễn231234', 'Dương231234', '0337273658231234', 'c3tanlaphanoi@gmail.com231234', 's08', 032),
('a99c5748-8d3c-11ee-992a-1063c83412cc', 'Nguyễn3', 'Dương3', '03372736583', 'c3tanlaphanoi@gmail.com3', 's09', 033);

-- 
-- Dumping data for table teacherclasses
--
-- Table nvduong.teacherclasses does not contain any data (it is empty)

-- 
-- Dumping data for table scores
--
INSERT INTO scores VALUES
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 1, 5, 6, 4, 9, 4, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 1, 5, 4, 5, 2, 6, 1, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 1, 6, 5, 5, 10, 6, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 2, 4, 1, 1, 2, 6, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 2, 1, 3, 1, 7, 1, 1, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's01', 2, 9, 3, 6, 2, 3, 7, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 1, 9, 9, 7, 7, 5, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 1, 9, 1, 9, 1, 6, 8, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 1, 5, 1, 6, 6, 1, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 2, 9, 7, 8, 7, 3, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 2, 4, 8, 5, 1, 8, 7, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's02', 2, 6, 7, 8, 9, 1, 6, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 1, 5, 3, 8, 2, 3, 10, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 1, 2, 7, 5, 6, 6, 9, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 1, 10, 4, 8, 7, 9, 6, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 2, 10, 7, 6, 7, 5, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 2, 10, 1, 3, 3, 3, 5, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's03', 2, 9, 5, 7, 10, 7, 5, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 1, 9, 4, 2, 10, 4, 8, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 1, 5, 10, 3, 6, 1, 6, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 1, 10, 2, 9, 7, 10, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 2, 3, 5, 3, 1, 5, 3, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 2, 6, 6, 1, 5, 4, 5, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's04', 2, 2, 5, 9, 10, 10, 3, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 1, 7, 9, 6, 2, 10, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 1, 4, 4, 9, 9, 10, 1, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 1, 4, 1, 3, 4, 8, 6, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 2, 9, 7, 8, 6, 6, 2, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 2, 1, 1, 10, 8, 1, 7, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's05', 2, 1, 7, 1, 3, 3, 7, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 1, 1, 1, 3, 10, 9, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 1, 4, 9, 10, 4, 10, 7, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 1, 9, 5, 7, 1, 4, 7, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 2, 9, 2, 1, 9, 3, 5, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 2, 5, 1, 10, 5, 8, 2, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's06', 2, 3, 3, 6, 2, 10, 3, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 1, 2, 10, 5, 6, 3, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 1, 6, 7, 8, 6, 6, 2, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 1, 3, 3, 7, 3, 4, 10, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 2, 7, 8, 10, 4, 2, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 2, 4, 6, 7, 8, 7, 10, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's07', 2, 4, 3, 1, 4, 6, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 1, 2, 9, 9, 9, 6, 4, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 1, 9, 2, 3, 6, 3, 6, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 1, 7, 4, 9, 4, 1, 4, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 2, 4, 1, 1, 4, 5, 2, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 2, 9, 5, 8, 2, 6, 4, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's08', 2, 5, 9, 8, 5, 8, 6, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 1, 2, 9, 6, 4, 2, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 1, 9, 5, 10, 5, 5, 1, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 1, 6, 6, 2, 1, 1, 10, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 2, 5, 7, 10, 9, 6, 10, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 2, 1, 1, 2, 7, 10, 6, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's09', 2, 6, 2, 9, 9, 9, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 1, 2, 4, 3, 2, 9, 9, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 1, 6, 8, 3, 9, 4, 4, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 1, 6, 9, 9, 6, 4, 1, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 2, 1, 7, 10, 7, 7, 2, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 2, 9, 6, 3, 7, 6, 8, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's10', 2, 5, 9, 1, 5, 4, 2, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 1, 6, 5, 7, 9, 5, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 1, 7, 4, 8, 5, 3, 8, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 1, 1, 2, 8, 1, 1, 10, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 2, 10, 3, 3, 6, 2, 1, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 2, 3, 10, 9, 4, 4, 5, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's11', 2, 9, 10, 1, 5, 3, 9, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 1, 6, 2, 1, 8, 7, 8, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 1, 1, 9, 1, 10, 6, 8, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 1, 9, 6, 10, 1, 5, 3, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 2, 7, 1, 3, 2, 10, 3, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 2, 5, 1, 6, 7, 9, 1, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's12', 2, 6, 1, 8, 7, 9, 3, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 1, 1, 10, 7, 5, 2, 6, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 1, 3, 10, 2, 9, 6, 4, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 1, 7, 7, 4, 7, 3, 4, 3),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 2, 6, 2, 9, 9, 7, 7, 1),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 2, 7, 1, 5, 9, 3, 5, 2),
('ce0204eb-8dd8-11ee-992a-1063c83412cc', 'd3b81196-8d3a-11ee-992a-1063c83412cc', 's13', 2, 10, 8, 9, 10, 4, 1, 3);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;